### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by jich77** [ScotPHO/scotpho-profiles-tool#42]
Warning in gzfile(file, "rb") :
  cannot open compressed file 'data/deprivation_data.rds', probable reason 'No such file or directory'
Error in gzfile(file, "rb") : cannot open the connection

**Comment by jvillacampa** [comment]
Hi @jich77, thanks for spotting that. We have added the file now.

**Comment by jich77** [comment]
Thank you very much for adding the file. I really like  your work

 

 

Saludos/Med venlig hilsen/Best Regards

 

Javier I. Camacho

Msc.Eng

(+45)81193892

 <mailto:eng.javiercamacho@gmail.com> eng.javiercamacho@gmail.com
